import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import ThemePicker from "@/components/ThemePicker";
import LanguagePicker from "@/components/LanguagePicker";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} border-box bg-primary dark:bg-white`}
      >
        <div className="flex w-full gap-8 p-6 px-8  fixed justify-end items-center">
          <ThemePicker />
          <LanguagePicker />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
